name: Default Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 20 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "free-ignorance/rite"
        run: docker build -t free-ignorance/rite .
      - name: Run The Lints . . .
        run: docker run free-ignorance/rite npm run test:lint
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 20 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "free-ignorance/rite"
        run: docker build -t free-ignorance/rite .
      - name: Run The Tests . . .
        run: docker run free-ignorance/rite npm run test

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 20 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Run The Tests . . .
        run: npm run test:coverage 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: free-ignorance/rite